### ISSUE TITLE
Rework the documentation flow

### ISSUE THREAD

**Issue by riderx** [Cap-go/website#106]
The current documentation is not clear for users and would need to be re-ordered and cleaned.
The goal is to help to achieve the AHA moment of Capgo and doc has to improve it.
Then the doc has to be interesting for advanced users

**Comment by Ashutosh-Bhadauriya** [comment]
@riderx I would like to take this 
/attempt #106

**Comment by rishi-raj-jain** [comment]
@riderx

/attempt #106

**Comment by rishi-raj-jain** [comment]
I'm taking off myself on this. In case you feel like not dong / passing this, @Ashutosh-Bhadauriya do lmk.

**Comment by riderx** [comment]
Someone on Twitter shared about this: https://diataxis.fr/
it seems a good way to structure documentation

**Comment by Ashutosh-Bhadauriya** [comment]
@riderx I went through the capgo docs. Are you sure only the restructuring would help. I think we need to redo some content here.

Here are some of the docs I really like, not related to capgo though, maybe some inspiration can be taken from them
https://resend.com/docs/introduction
https://trigger.dev/docs/documentation/introduction
https://infisical.com/docs/documentation/getting-started/introduction

**Comment by rishi-raj-jain** [comment]
@Ashutosh-Bhadauriya 

FYI

https://capgo.app/docs/ are on starlight.astro.build a docusarus like project by Astro

**Comment by riderx** [comment]
@Ashutosh-Bhadauriya yes you are totally right there a lot to do.
For the tech stack @rishi-raj-jain did the migration a week ago, and i'm pretty satisfied for now, so let's keep it like that for now.

**Comment by WcaleNieWolny** [comment]
https://github.com/Cap-go/website/issues/110

**Comment by WcaleNieWolny** [comment]
No I am not, I have revived my bounty for S3 docs

**Comment by WcaleNieWolny** [comment]
Feel free to take this

**Comment by WcaleNieWolny** [comment]
@anikdhabal what is the status of your attempt? I would love to attempt this if this is available

**Comment by anikdhabal** [comment]
> @anikdhabal what is the status of your attempt? I would love to attempt this if this is available
> 
> As a contributor to the capgo project I know a lot about and and it would be relatively easy for me to document the project and all the different features that we have available

Yes @WcaleNieWolny. I am taking off. You can try

**Comment by WcaleNieWolny** [comment]
Thanks a lot 🙏

/attempt #106

**Comment by WcaleNieWolny** [comment]
here is the list of articles I think would be beneficial to add:

 * [CI/CD integration](https://github.com/Cap-go/CLI/pull/132)
 * AB testing (how to enable and use AB testing)
 * Progressive deploy (@riderx progressive deploy even work or was it disabled?)
 * [Selecting disabling update strategy](https://github.com/Cap-go/capgo/pull/405)
 * Add contributing guidelines (link [contributing.md](https://github.com/Cap-go/capgo/blob/main/CONTRIBUTING.md))
  * Fix misleading information in existing tutorials + fix typos
