### ISSUE TITLE
Programatic SEO

### ISSUE THREAD

**Issue by riderx** [Cap-go/website#107]
Create automatic page for every Capacitor plugin is in Capgo org, and list them here: 
https://capgo.app/plugins/
Design should be changed.
Each plugin should have his page at : https://capgo.app/plugins/NAME
Each plugin page should show README info, GitHub stars, NPM download and have link to GitHub and NPM
We can maybe use GPT to generate a basic tutorial for each.

**Comment by rishi-raj-jain** [comment]
@riderx 

/attempt @107

**Comment by rishi-raj-jain** [comment]
@riderx 

Can I get access to all the plugins? Where do I find those?

**Comment by riderx** [comment]
They are here in github
https://github.com/orgs/Cap-go/repositories?type=source

Can be also found in npm:
https://www.npmjs.com/search?q=@capgo
