### ISSUE TITLE
Check typo and mistakes

### ISSUE THREAD

**Issue by riderx** [Cap-go/website#109]
look all the website, blog and doc and check copywriting

**Comment by rishi-raj-jain** [comment]
What do you mean by copywriting?

**Comment by rishi-raj-jain** [comment]
@neo773 

Are you on this anymore?

**Comment by neo773** [comment]
@rishi-raj-jain It’s done, but martin busy’s with other stuff so it’s awaiting review

**Comment by rishi-raj-jain** [comment]
Oh okay, just didn't see the PR hence asked.

**Comment by neo773** [comment]
@rishi-raj-jain It's easier to see these visual changes on a live tunnel than commit diffs so that's why i haven't made the actual commit yet.

**Comment by rishi-raj-jain** [comment]
This shall be closed, right?

**Comment by riderx** [comment]
yes !
