### ISSUE TITLE
Improve self hosting docs

### ISSUE THREAD

**Issue by WcaleNieWolny** [Cap-go/website#110]
Currently there is no mention in the docs how to:
 * Self host S3 ([minio](https://min.io/))
 * Use self hosted capgo in the ios/android plugin
 * Start edge functions
 * What services are not available by default on self hosted capgo
 * How to make sure these services work

This issue prevents a lot of code from ever being accessed by bounty hunters thus leading to some issues not being solved ([like this email issue](https://github.com/Cap-go/capgo/issues/280) or [this S3 issue](https://github.com/Cap-go/capgo/issues/270))

**Comment by WcaleNieWolny** [comment]
If there ever is a bounty created for this I would love to attempt it.

I already solved most of these issue, and I just how to document how I did it

**Comment by tungpham-dev** [comment]
Hi! I've opened a PR that addresses all the gaps mentioned in this issue — MinIO/S3 setup, connecting the iOS/Android plugin to a self-hosted instance, starting edge functions, what services are unavailable, and SMTP configuration. Happy to revise anything!
