### ISSUE TITLE
Issue with strutured data

### ISSUE THREAD

**Issue by riderx** [Cap-go/website#154]
![CleanShot 2023-12-02 at 17 00 43@2x](https://github.com/Cap-go/website/assets/4084527/c1aafac4-17f5-4ff9-aa37-7e62d4b9c26d)
Google console is showing issue with our structured data, i'm not sure what is require to fix it

**Comment by rishi-raj-jain** [comment]
/attempt #154 I'll be on fixing this just after table of content.
