### ISSUE TITLE
Create CI step to deploy website to Cloudflare workers

### ISSUE THREAD

**Issue by riderx** [Cap-go/website#174]
The goal is to stop using Netlify deploy and instead use Cloudflare worker to deploy.

It should be integrated in GitHub Actions CI in the end of build step

**Comment by riderx** [comment]
just replicate the process of here: https://github.com/Cap-go/capgo/issues/540

**Comment by rajdip-b** [comment]
Can I be assigned?

**Comment by rishi-raj-jain** [comment]
Can I be assigned?
