### ISSUE TITLE
Website says pricing is not yet implemented, but it seems like it is now

### ISSUE THREAD

**Issue by thgh** [Cap-go/website#34]
PLEASE READ: I originally made this template for myself to mocking up apps quicker. I am glad to see you are willing to give it a try! Before your open the issue, please make sure you are reporting bugs in the template itself. **I am NOT creating this template to solve the problems you faced in your project, please use Vue or Vite's discord server to ask questions (or it might be closed directly without further notice).** Thank you.

**Describe the bug/issue**

**Comment by riderx** [comment]
@thgh can you share screenshot ? it seems cache problem again.

**Comment by thgh** [comment]
Looks like a rogue service worker (Received 15/04/2022, 09:54:00)

You may want to add an empty service worker at that URL, if Chrome can't find it, it will keep the current one forever.

![Screenshot 2022-09-07 at 16 18 35](https://user-images.githubusercontent.com/1109982/188901678-7552c0de-caa2-4f49-9965-0dbd78b135ac.png)

**Comment by thgh** [comment]
More info:
<img width="1144" alt="Screenshot 2022-09-07 at 16 23 14" src="https://user-images.githubusercontent.com/1109982/188902718-75fca16f-394c-4e94-93dc-ce66bee377b4.png">

**Comment by riderx** [comment]
@YacineMessaadi can you try it ?

**Comment by YacineMessaadi** [comment]
Yes I will look at it

**Comment by YacineMessaadi** [comment]
@thgh I've added a sw.js, can you retry and tell me if it works ?

**Comment by thgh** [comment]
Doesn't work yet, turns out you need [skipWaiting](https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorkerGlobalScope/skipWaiting): (the fetch event may be unnecessary
```
self.addEventListener("install", (event) => {
  self.skipWaiting();
});
```

**Comment by riderx** [comment]
i did added it, can you check again ?

**Comment by thgh** [comment]
Perfect!
