### ISSUE TITLE
First call to action on homepage shows empty page

### ISSUE THREAD

**Issue by thgh** [Cap-go/website#36]
It looks like this
<img width="816" alt="Screenshot 2022-09-06 at 16 56 45" src="https://user-images.githubusercontent.com/1109982/188668177-c179fc93-8c7b-428f-af13-9f5c9d7c0cc2.png">

**Comment by riderx** [comment]
@thgh nothing load ? it should remove after 0.5 sec max to show the app

**Comment by thgh** [comment]
Try visiting https://web.capgo.app/register in an incognito window
