### ISSUE TITLE
Bottom call to action on homepage goes to 404

### ISSUE THREAD

**Issue by thgh** [Cap-go/website#37]
It looks like this:
<img width="772" alt="Screenshot 2022-09-06 at 16 57 55" src="https://user-images.githubusercontent.com/1109982/188668412-acc51ffa-cf6b-47fc-85bd-13f9823896ba.png">

**Comment by riderx** [comment]
Hey @thgh i don't find this link in the code or looking in the website can you show a screenshot ?

**Comment by thgh** [comment]
Alright, it works now
