### ISSUE TITLE
Write blog article about quasar config with capgo

### ISSUE THREAD

**Issue by riderx** [Cap-go/website#42]

**Comment by Akshay-Patel-dev** [comment]
/attempt #42 , I am going with this one.

Take time but complete asap.

**Comment by riderx** [comment]
Thanks a lot !

**Comment by ayusham001** [comment]
Hi @riderx, in the blog do I have to add any head image?

**Comment by riderx** [comment]
@ayusham001 the blog article expected is 2500 worlds minimum.
With illustration images of steps, and explain from zero the app creation with capacitor etc.
only capgo way automatic not manual update
