### ISSUE TITLE
fix stats display in landing

### ISSUE THREAD

**Issue by riderx** [Cap-go/website#62]

**Comment by rishi-raj-jain** [comment]
@riderx 

Which stats is this regarding?

**Comment by riderx** [comment]
The MAU, storage and bandwidth.
It’s now stored in app_usage.
And should be displayed in relation with user cycle start and end.
I made a rcp for that

**Comment by riderx** [comment]
It should be done by app and globally

**Comment by riderx** [comment]
Sorry guys i made this issue in the wrong repo, it should be in capgo

**Comment by rishi-raj-jain** [comment]
No worries

**Comment by rishi-raj-jain** [comment]
Would love to get the bounty + tip (for improving the `lint` & `test` workflow)!
